from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
import os
import tempfile
import json

def generate_pdf(curriculum, output_path=None):
    # Create temp file if no path provided (Windows safe)
    if output_path is None:
        fd, output_path = tempfile.mkstemp(suffix='.pdf')
        os.close(fd)
    
    try:
        doc = SimpleDocTemplate(output_path, pagesize=A4, 
                               rightMargin=72, leftMargin=72,
                               topMargin=72, bottomMargin=72)
        styles = getSampleStyleSheet()
        
        # Custom styles
        title_style = ParagraphStyle(
            'Title',
            parent=styles['Heading1'],
            fontSize=24,
            textColor=colors.HexColor('#1a365d'),
            spaceAfter=30,
            alignment=1
        )
        
        heading_style = ParagraphStyle(
            'Heading',
            parent=styles['Heading2'],
            fontSize=16,
            textColor=colors.HexColor('#2c5282'),
            spaceAfter=12,
            spaceBefore=12
        )
        
        subheading_style = ParagraphStyle(
            'SubHeading',
            parent=styles['Heading3'],
            fontSize=14,
            textColor=colors.HexColor('#2b6cb0'),
            spaceAfter=8
        )
        
        normal_style = ParagraphStyle(
            'Normal',
            parent=styles['Normal'],
            fontSize=11,
            spaceAfter=6,
            leading=14
        )
        
        story = []
        
        # Title page
        story.append(Spacer(1, 1.5*inch))
        story.append(Paragraph(curriculum.get('program_title', 'Learning Plan'), title_style))
        story.append(Spacer(1, 0.3*inch))
        story.append(Paragraph(f"<b>Industry Focus:</b> Technology", 
                              ParagraphStyle(parent=styles['Normal'], fontSize=12, alignment=1)))
        story.append(Spacer(1, 0.2*inch))
        story.append(Paragraph(f"<b>Duration:</b> {len(curriculum.get('semesters', []))} Semesters", 
                              ParagraphStyle(parent=styles['Normal'], fontSize=12, alignment=1)))
        story.append(Spacer(1, 0.5*inch))
        story.append(Paragraph("<i>Generated by GenAI Curriculum Tracker</i>", 
                              ParagraphStyle(parent=styles['Normal'], fontSize=10, alignment=1, textColor=colors.grey)))
        story.append(PageBreak())
        
        # Overview
        story.append(Paragraph("Program Overview", heading_style))
        story.append(Paragraph(curriculum.get('overview', 'Comprehensive learning program'), normal_style))
        story.append(Spacer(1, 0.3*inch))
        
        # Semesters
        for semester in curriculum.get('semesters', []):
            story.append(PageBreak())
            story.append(Paragraph(f"Semester {semester.get('semester', 1)}", heading_style))
            story.append(Spacer(1, 0.2*inch))
            
            for course in semester.get('courses', []):
                story.append(Paragraph(course.get('course_name', 'Course'), subheading_style))
                
                # Topics - handle both string arrays and object arrays
                topics = course.get('topics', [])
                if topics and len(topics) > 0:
                    # Convert object topics to strings if needed
                    topic_strings = []
                    for t in topics:
                        if isinstance(t, dict):
                            topic_strings.append(t.get('name', str(t)))
                        else:
                            topic_strings.append(str(t))
                    
                    story.append(Paragraph("<b>Topics:</b>", normal_style))
                    for topic in topic_strings:
                        story.append(Paragraph(f"• {topic}", normal_style))
                
                # Hours
                hours = course.get('hours_per_week', 0)
                if hours:
                    story.append(Paragraph(f"<b>Weekly Hours:</b> {hours}", normal_style))
                
                # Project
                project = course.get('project_idea', '')
                if project:
                    story.append(Paragraph(f"<b>Project:</b> {project}", 
                                          ParagraphStyle(parent=styles['Normal'], textColor=colors.HexColor('#22c55e'))))
                
                story.append(Spacer(1, 0.3*inch))
        
        # Capstone
        capstone = curriculum.get('capstone_project', '')
        if capstone:
            story.append(PageBreak())
            story.append(Paragraph("Capstone Project", heading_style))
            story.append(Paragraph(capstone, normal_style))
        
        doc.build(story)
        return output_path
        
    except Exception as e:
        # Log error for debugging
        error_log = f"PDF generation error: {str(e)}\nCurriculum: {json.dumps(curriculum, indent=2)[:500]}"
        print(error_log)
        raise